services:
  js-backend:
    build:
      context: ./backend
      dockerfile: ../backendDockerfile
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000" 
    networks:
      - appnet


  ts-root:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true

    networks:
      - appnet

    depends_on:
      - js-backend

networks:
  appnet:
    driver: bridge
